import { useMemo, useState } from 'react';
import {
  AlertTriangle,
  CheckCircle2,
  ChevronDown,
  ExternalLink,
  HelpCircle,
  Info,
  Quote,
  ShieldAlert,
  XCircle,
} from 'lucide-react';
import { Badge, Button, Tooltip, cn } from '@uxe/ui';
import {
  formatLocator,
  type AnswerStyle,
  type Citation,
  type ComplianceResult,
  type StructuredAnswer,
} from '@uxe/contracts';
import { useI18n } from '../lib/i18n.js';
import { ComplianceChecklist, Tickbox, labelKeyFor } from './ComplianceChecklist.js';

export interface AnswerViewProps {
  answer: StructuredAnswer;
  style: AnswerStyle;
  evidenceDetail: {
    documentAndPage: boolean;
    clauseAndLocation: boolean;
    supportingExcerpt: boolean;
  };
  onOpenCitation: (citationId: string) => void;
  onViewAllCitations: () => void;
  actions?: React.ReactNode;
}

const RESULT_META: Record<
  ComplianceResult,
  {
    tone: 'success' | 'danger' | 'warning' | 'neutral';
    icon: typeof CheckCircle2;
    labelKey: string;
  }
> = {
  compliant: { tone: 'success', icon: CheckCircle2, labelKey: 'compliance.compliant' },
  non_compliant: { tone: 'danger', icon: XCircle, labelKey: 'compliance.nonCompliant' },
  needs_evidence: { tone: 'warning', icon: AlertTriangle, labelKey: 'compliance.needsEvidence' },
  not_assessed: { tone: 'neutral', icon: HelpCircle, labelKey: 'compliance.notAssessed' },
};

/**
 * Renders one structured answer at the requested depth.
 *
 * All three styles are projections of the SAME `answer` object. Switching style re-renders
 * from the evidence already verified; it never triggers new retrieval, so the three views
 * can never contradict one another.
 */
export function AnswerView({
  answer,
  style,
  evidenceDetail,
  onOpenCitation,
  onViewAllCitations,
  actions,
}: AnswerViewProps) {
  const { t } = useI18n();

  const decisive = useMemo(() => pickDecisive(answer, style === 'yes_no' ? 3 : 6), [answer, style]);

  return (
    <div className="flex flex-col gap-4" data-answer-root>
      {answer.injectionWarnings.length > 0 && (
        <InjectionWarning warnings={answer.injectionWarnings} />
      )}

      <DecisionHeader answer={answer} style={style} />

      {style === 'yes_no' ? (
        <YesNoBody
          answer={answer}
          citations={decisive}
          onOpenCitation={onOpenCitation}
          evidenceDetail={evidenceDetail}
        />
      ) : style === 'optimal' ? (
        <OptimalBody
          answer={answer}
          citations={decisive}
          onOpenCitation={onOpenCitation}
          evidenceDetail={evidenceDetail}
        />
      ) : (
        <DetailsBody
          answer={answer}
          onOpenCitation={onOpenCitation}
          evidenceDetail={evidenceDetail}
        />
      )}

      {answer.followUpQuestion && (
        <div className="flex items-start gap-3 rounded-[var(--uxe-radius-card)] border border-[var(--uxe-info-border)] bg-[var(--uxe-info-bg)] p-3.5">
          <HelpCircle className="mt-0.5 h-4 w-4 shrink-0 text-[var(--uxe-info)]" aria-hidden />
          <p className="text-[13px] text-[var(--uxe-text)]">{answer.followUpQuestion}</p>
        </div>
      )}

      {answer.usedGeneralModel && (
        <p className="flex items-center gap-2 text-[12px] font-medium text-[var(--uxe-warning)]">
          <Info className="h-3.5 w-3.5" aria-hidden />
          Some statements came from the general model rather than your sources and are labelled
          inline.
        </p>
      )}

      <div className="flex flex-wrap items-center gap-2 border-t border-[var(--uxe-border)] pt-3">
        {answer.citations.length > 0 && (
          <Button variant="secondary" size="sm" onClick={onViewAllCitations}>
            <Quote className="h-3.5 w-3.5" aria-hidden />
            {t('consult.viewAllCitations')} ({answer.citations.length})
          </Button>
        )}
        {actions}
      </div>

      <p className="text-[11px] text-[var(--uxe-text-tertiary)]">
        Generated by {answer.modelDescriptor}
      </p>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* Decision header                                                            */
/* -------------------------------------------------------------------------- */

function DecisionHeader({ answer, style }: { answer: StructuredAnswer; style: AnswerStyle }) {
  const { t } = useI18n();

  const tone =
    answer.decision === 'unable_to_determine'
      ? 'neutral'
      : answer.decisionQualifier
        ? 'warning'
        : answer.decision === 'no'
          ? 'danger'
          : answer.decision === 'yes'
            ? 'success'
            : 'brand';

  const Icon =
    tone === 'success'
      ? CheckCircle2
      : tone === 'danger'
        ? XCircle
        : tone === 'warning'
          ? AlertTriangle
          : Info;

  // Yes/No must lead with the literal word, so it is rendered as its own line.
  const headline =
    answer.decision === 'yes'
      ? t('compliance.yes')
      : answer.decision === 'no'
        ? t('compliance.no')
        : answer.decision === 'unable_to_determine'
          ? t('compliance.unableToDetermine').toUpperCase()
          : null;

  const toneStyles = {
    success: 'border-[var(--uxe-success-border)] bg-[var(--uxe-success-bg)]',
    danger: 'border-[var(--uxe-danger-border)] bg-[var(--uxe-danger-bg)]',
    warning: 'border-[var(--uxe-warning-border)] bg-[var(--uxe-warning-bg)]',
    neutral: 'border-[var(--uxe-border)] bg-[var(--uxe-surface-sunken)]',
    brand: 'border-[var(--uxe-border)] bg-[var(--uxe-surface-sunken)]',
  } as const;

  const iconStyles = {
    success: 'text-[var(--uxe-success)]',
    danger: 'text-[var(--uxe-danger)]',
    warning: 'text-[var(--uxe-warning)]',
    neutral: 'text-[var(--uxe-text-secondary)]',
    brand: 'text-[var(--uxe-cobalt)]',
  } as const;

  return (
    <div
      className={cn(
        'flex items-start gap-3.5 rounded-[var(--uxe-radius-card)] border p-4',
        toneStyles[tone],
      )}
    >
      <Icon className={cn('mt-0.5 h-6 w-6 shrink-0', iconStyles[tone])} aria-hidden />

      <div className="min-w-0 flex-1">
        {headline && (
          <p className={cn('text-[15px] font-bold tracking-wide uppercase', iconStyles[tone])}>
            {headline}
            {/* Partial compliance is shown alongside NO, never instead of it. */}
            {answer.decisionQualifier && (
              <span className="ms-2 rounded-[var(--uxe-radius-pill)] bg-[var(--uxe-warning)] px-2 py-0.5 text-[11px] font-semibold text-white uppercase">
                {answer.decisionQualifier}
              </span>
            )}
          </p>
        )}
        <h3 className={cn('text-[18px] font-bold text-[var(--uxe-text)]', headline && 'mt-1')}>
          {answer.headline}
        </h3>
        {answer.documentsReviewed.length > 0 && (
          <p className="mt-1 text-[13px] text-[var(--uxe-text-secondary)]">
            Based on {answer.documentsReviewed.filter((d) => d.role === 'governing').length}{' '}
            regulation
            {answer.documentsReviewed.filter((d) => d.role === 'governing').length === 1
              ? ''
              : 's'}{' '}
            and {answer.documentsReviewed.filter((d) => d.role === 'project').length} project
            document
            {answer.documentsReviewed.filter((d) => d.role === 'project').length === 1 ? '' : 's'}
          </p>
        )}
      </div>

      {style !== 'yes_no' && <ConfidenceBadge answer={answer} />}
    </div>
  );
}

function ConfidenceBadge({ answer }: { answer: StructuredAnswer }) {
  const { t } = useI18n();
  const percent = Math.round(answer.confidence.overall * 100);
  const c = answer.confidence;

  return (
    <Tooltip
      content={
        <span className="block space-y-1">
          <span className="block font-semibold">{t('answer.howCalculated')}</span>
          <span className="block">Evidence coverage {Math.round(c.evidenceCoverage * 100)}%</span>
          <span className="block">Retrieval quality {Math.round(c.retrievalQuality * 100)}%</span>
          <span className="block">
            Citation verification {Math.round(c.citationVerification * 100)}%
          </span>
          <span className="block">Source authority {Math.round(c.sourceAuthority * 100)}%</span>
          <span className="block">Recency {Math.round(c.recency * 100)}%</span>
          <span className="block">
            Contradiction factor {Math.round(c.contradictionPenalty * 100)}%
          </span>
        </span>
      }
    >
      {/* A button, not a focusable span: the derivation must be reachable by keyboard. */}
      <button
        type="button"
        className={cn(
          'shrink-0 cursor-help rounded-[var(--uxe-radius-pill)] px-2.5 py-1 text-[12px] font-semibold',
          percent >= 80
            ? 'bg-[var(--uxe-success-bg)] text-[var(--uxe-success-text)]'
            : percent >= 55
              ? 'bg-[var(--uxe-warning-bg)] text-[var(--uxe-warning-text)]'
              : 'bg-[var(--uxe-neutral-bg)] text-[var(--uxe-text-secondary)]',
        )}
      >
        {percent}% confidence
      </button>
    </Tooltip>
  );
}

/* -------------------------------------------------------------------------- */
/* Yes / No                                                                   */
/* -------------------------------------------------------------------------- */

function YesNoBody({
  answer,
  citations,
  onOpenCitation,
  evidenceDetail,
}: {
  answer: StructuredAnswer;
  citations: Citation[];
  onOpenCitation: (id: string) => void;
  evidenceDetail: AnswerViewProps['evidenceDetail'];
}) {
  return (
    <div className="flex flex-col gap-3">
      {answer.decisiveReason && (
        <p className="text-[15px] leading-relaxed text-[var(--uxe-text)]">
          {answer.decisiveReason}
        </p>
      )}
      {citations.length > 0 && (
        <ul className="flex flex-col gap-2">
          {citations.map((citation) => (
            <li key={citation.citationId}>
              <CitationChip
                citation={citation}
                onOpen={onOpenCitation}
                evidenceDetail={evidenceDetail}
              />
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* Optimal                                                                    */
/* -------------------------------------------------------------------------- */

function OptimalBody({
  answer,
  citations,
  onOpenCitation,
  evidenceDetail,
}: {
  answer: StructuredAnswer;
  citations: Citation[];
  onOpenCitation: (id: string) => void;
  evidenceDetail: AnswerViewProps['evidenceDetail'];
}) {
  const { t } = useI18n();

  return (
    <div className="flex flex-col gap-4">
      <p className="text-[15px] leading-relaxed text-[var(--uxe-text)]">{answer.summary}</p>

      {/*
        A compliance check is answered as a checklist, not a paragraph: every obligation
        tested gets its own line and its own box. The compact table below still serves the
        other task modes, where findings are incidental rather than the whole answer.
      */}
      {answer.task === 'check_compliance' && answer.findings.length > 0 && (
        <ComplianceChecklist
          answer={answer}
          onOpenCitation={onOpenCitation}
          evidenceDetail={evidenceDetail}
        />
      )}

      {answer.task !== 'check_compliance' && answer.findings.length > 0 && (
        <div className="overflow-hidden rounded-[var(--uxe-radius-card)] border border-[var(--uxe-border)]">
          <table className="w-full border-collapse text-start">
            <caption className="sr-only">{t('answer.compactTable')}</caption>
            <tbody>
              {answer.findings.slice(0, 8).map((finding) => {
                const meta = RESULT_META[finding.result];
                const ResultIcon = meta.icon;
                const citationId =
                  finding.governingCitationIds[0] ?? finding.projectEvidenceCitationIds[0] ?? null;
                const citation = citationId
                  ? (answer.citations.find((c) => c.citationId === citationId) ?? null)
                  : null;

                return (
                  <tr
                    key={finding.findingId}
                    className="border-b border-[var(--uxe-border)] last:border-0"
                  >
                    <td className="w-8 py-2.5 ps-3">
                      <ResultIcon
                        className={cn(
                          'h-4 w-4',
                          meta.tone === 'success'
                            ? 'text-[var(--uxe-success)]'
                            : meta.tone === 'danger'
                              ? 'text-[var(--uxe-danger)]'
                              : meta.tone === 'warning'
                                ? 'text-[var(--uxe-warning)]'
                                : 'text-[var(--uxe-text-tertiary)]',
                        )}
                        aria-hidden
                      />
                    </td>
                    <td className="py-2.5 pe-3 text-[14px] font-medium text-[var(--uxe-text)]">
                      {finding.requirementTitle || finding.requirementReference}
                    </td>
                    <td className="py-2.5 pe-3">
                      <Badge tone={meta.tone} size="sm">
                        {t(meta.labelKey as 'compliance.compliant')}
                      </Badge>
                    </td>
                    <td className="py-2.5 pe-3 text-end">
                      {citation ? (
                        <button
                          type="button"
                          onClick={() => onOpenCitation(citation.citationId)}
                          className="text-[12px] text-[var(--uxe-text-secondary)] hover:text-[var(--uxe-cobalt)] hover:underline"
                        >
                          {citation.documentTitle} · {formatLocator(citation)}
                        </button>
                      ) : (
                        <span className="text-[12px] text-[var(--uxe-text-tertiary)]">
                          {t('answer.noLocatedEvidence')}
                        </span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {answer.keyFindings.length > 0 && answer.findings.length === 0 && (
        <ul className="flex flex-col gap-1.5">
          {answer.keyFindings.map((finding, index) => (
            <li key={index} className="flex items-start gap-2 text-[14px] text-[var(--uxe-text)]">
              <span
                aria-hidden
                className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--uxe-cobalt)]"
              />
              {finding}
            </li>
          ))}
        </ul>
      )}

      {citations[0] && (
        <CitationChip
          citation={citations[0]}
          onOpen={onOpenCitation}
          evidenceDetail={evidenceDetail}
          featured
        />
      )}

      {answer.recommendedActions.length > 0 && (
        <section>
          <h4 className="text-[13px] font-semibold tracking-wide text-[var(--uxe-text-secondary)] uppercase">
            {t('evidence.recommendedActions')}
          </h4>
          <ul className="mt-2 flex flex-col gap-1.5">
            {answer.recommendedActions.map((action, index) => (
              <li key={index} className="flex items-start gap-2 text-[14px] text-[var(--uxe-text)]">
                <Badge
                  tone={
                    action.priority === 'critical'
                      ? 'danger'
                      : action.priority === 'high'
                        ? 'warning'
                        : 'neutral'
                  }
                  size="sm"
                >
                  {action.priority}
                </Badge>
                <span className="min-w-0">{action.action}</span>
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* Details + references                                                       */
/* -------------------------------------------------------------------------- */

function DetailsBody({
  answer,
  onOpenCitation,
  evidenceDetail,
}: {
  answer: StructuredAnswer;
  onOpenCitation: (id: string) => void;
  evidenceDetail: AnswerViewProps['evidenceDetail'];
}) {
  const { t } = useI18n();
  const byId = useMemo(
    () => new Map(answer.citations.map((c) => [c.citationId, c])),
    [answer.citations],
  );

  return (
    <div className="flex flex-col gap-5">
      <Section title={t('evidence.scope')}>
        <p className="text-[14px] text-[var(--uxe-text)]">{answer.scope ?? answer.summary}</p>
      </Section>

      {answer.documentsReviewed.length > 0 && (
        <Section title={t('evidence.documentsReviewed')}>
          <ul className="flex flex-col gap-1.5">
            {answer.documentsReviewed.map((doc) => (
              <li
                key={doc.sourceVersionId}
                className="flex flex-wrap items-center gap-2 text-[13px]"
              >
                <Badge tone={doc.role === 'governing' ? 'brand' : 'teal'} size="sm">
                  {doc.role === 'governing' ? 'Regulation' : 'Project'}
                </Badge>
                <span className="font-medium text-[var(--uxe-text)]">{doc.title}</span>
                <span className="text-[var(--uxe-text-secondary)]">
                  {doc.version}
                  {doc.pages ? ` · ${doc.pages} pages` : ''}
                </span>
                {/*
                  Which sheets were actually opened. Without it "the drawing does not show
                  it" is indistinguishable from "that sheet was never read".
                */}
                {doc.sheetsInspected.length > 0 && (
                  <span className="text-[var(--uxe-text-tertiary)]">
                    {t('evidence.sheetsInspected', {
                      count: String(doc.sheetsInspected.length),
                      sheets: formatSheetRanges(doc.sheetsInspected),
                    })}
                  </span>
                )}
              </li>
            ))}
          </ul>
        </Section>
      )}

      {answer.assumptions.length > 0 && (
        <Section title={t('evidence.assumptions')}>
          <BulletList items={answer.assumptions} />
        </Section>
      )}

      {/*
        The checklist leads the detailed view too, so the verdict a reader took from the
        shorter form is the first thing they meet here rather than something they have to
        reconstruct from a table. The matrix below is the evidence behind it — excerpts,
        confidence, verification — not a second opinion.
      */}
      {answer.task === 'check_compliance' && answer.findings.length > 0 && (
        <ComplianceChecklist
          answer={answer}
          onOpenCitation={onOpenCitation}
          evidenceDetail={evidenceDetail}
        />
      )}

      {answer.findings.length > 0 && (
        <Section title={t('answer.findingsCaption')}>
          <div className="overflow-x-auto rounded-[var(--uxe-radius-card)] border border-[var(--uxe-border)]">
            <table className="w-full min-w-[880px] border-collapse text-start text-[13px]">
              <caption className="sr-only">{t('answer.evidenceMatrix')}</caption>
              <thead>
                <tr className="border-b border-[var(--uxe-border)] bg-[var(--uxe-surface-sunken)]">
                  {[
                    t('evidence.requirement'),
                    t('evidence.result'),
                    t('evidence.finding'),
                    t('evidence.source'),
                    t('evidence.location'),
                    t('evidence.excerpt'),
                    'Confidence',
                  ].map((header) => (
                    <th
                      key={header}
                      scope="col"
                      className="px-3 py-2.5 font-semibold text-[var(--uxe-text-secondary)]"
                    >
                      {header}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {answer.findings.map((finding) => {
                  const meta = RESULT_META[finding.result];
                  const citationId =
                    finding.projectEvidenceCitationIds[0] ??
                    finding.governingCitationIds[0] ??
                    null;
                  const citation = citationId ? (byId.get(citationId) ?? null) : null;

                  return (
                    <tr
                      key={finding.findingId}
                      className="border-b border-[var(--uxe-border)] align-top last:border-0"
                    >
                      <th
                        scope="row"
                        className="px-3 py-3 text-start font-semibold text-[var(--uxe-text)]"
                      >
                        <span className="block">{finding.requirementReference}</span>
                        <span className="block font-normal text-[var(--uxe-text-secondary)]">
                          {finding.requirementTitle}
                        </span>
                      </th>
                      <td className="px-3 py-3">
                        {/* The same mark as the checklist, so the two views read alike. */}
                        <span className="flex items-center gap-2">
                          <Tickbox result={finding.result} label={t(labelKeyFor(finding.result))} />
                          <Badge tone={meta.tone} size="sm">
                            {t(labelKeyFor(finding.result))}
                          </Badge>
                        </span>
                      </td>
                      <td className="max-w-xs px-3 py-3 text-[var(--uxe-text)]">
                        {finding.finding}
                      </td>
                      <td className="px-3 py-3 text-[var(--uxe-text-secondary)]">
                        {citation?.documentTitle ?? '—'}
                      </td>
                      <td className="px-3 py-3">
                        {citation ? (
                          <button
                            type="button"
                            onClick={() => onOpenCitation(citation.citationId)}
                            className="text-start text-[var(--uxe-cobalt)] hover:underline"
                          >
                            {formatLocator(citation)}
                          </button>
                        ) : (
                          <span className="text-[var(--uxe-text-tertiary)]">—</span>
                        )}
                      </td>
                      <td className="max-w-sm px-3 py-3">
                        {citation && evidenceDetail.supportingExcerpt ? (
                          <span className="block text-[var(--uxe-text-secondary)] italic">
                            &ldquo;{citation.supportingExcerpt}&rdquo;
                          </span>
                        ) : (
                          <span className="text-[var(--uxe-text-tertiary)]">—</span>
                        )}
                      </td>
                      <td className="px-3 py-3 text-end text-[var(--uxe-text-secondary)] tabular-nums">
                        {Math.round(finding.confidence * 100)}%
                        {citation && !citation.verified && (
                          <Badge tone="warning" size="sm" className="ms-1">
                            {t('evidence.unverified')}
                          </Badge>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </Section>
      )}

      {answer.calculations.length > 0 && (
        <Section title={t('evidence.calculations')}>
          <ul className="flex flex-col gap-2">
            {answer.calculations.map((calc, index) => (
              <li
                key={index}
                className="rounded-[var(--uxe-radius-control)] bg-[var(--uxe-surface-sunken)] p-3 text-[13px]"
              >
                <span className="font-semibold text-[var(--uxe-text)]">{calc.label}</span>
                <span className="mt-1 block font-[family-name:var(--uxe-font-mono)] text-[var(--uxe-text-secondary)]">
                  {calc.expression} = {calc.value}
                </span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      {answer.conflicts.length > 0 && (
        <Section title={t('evidence.conflicts')} tone="warning">
          <BulletList items={answer.conflicts.map((c) => c.description)} />
        </Section>
      )}

      {answer.missingEvidence.length > 0 && (
        <Section title={t('evidence.missing')} tone="warning">
          <BulletList items={answer.missingEvidence} />
        </Section>
      )}

      {answer.uncertainties.length > 0 && (
        <Section title={t('evidence.uncertainties')} tone="warning">
          <BulletList items={answer.uncertainties} />
        </Section>
      )}

      {answer.recommendedActions.length > 0 && (
        <Section title={t('evidence.recommendedActions')}>
          <ul className="flex flex-col gap-2">
            {answer.recommendedActions.map((action, index) => (
              <li key={index} className="flex items-start gap-2 text-[14px]">
                <Badge
                  tone={
                    action.priority === 'critical'
                      ? 'danger'
                      : action.priority === 'high'
                        ? 'warning'
                        : 'neutral'
                  }
                  size="sm"
                >
                  {action.priority}
                </Badge>
                <span className="min-w-0 text-[var(--uxe-text)]">{action.action}</span>
              </li>
            ))}
          </ul>
        </Section>
      )}
    </div>
  );
}

function Section({
  title,
  children,
  tone,
}: {
  title: string;
  children: React.ReactNode;
  tone?: 'warning';
}) {
  return (
    <section>
      <h4
        className={cn(
          'mb-2 text-[13px] font-semibold tracking-wide uppercase',
          tone === 'warning' ? 'text-[var(--uxe-warning)]' : 'text-[var(--uxe-text-secondary)]',
        )}
      >
        {title}
      </h4>
      {children}
    </section>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="flex flex-col gap-1.5">
      {items.map((item, index) => (
        <li key={index} className="flex items-start gap-2 text-[14px] text-[var(--uxe-text)]">
          <span
            aria-hidden
            className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--uxe-text-tertiary)]"
          />
          {item}
        </li>
      ))}
    </ul>
  );
}

/* -------------------------------------------------------------------------- */
/* Citation chip                                                              */
/* -------------------------------------------------------------------------- */

export function CitationChip({
  citation,
  onOpen,
  evidenceDetail,
  featured,
}: {
  citation: Citation;
  onOpen: (id: string) => void;
  evidenceDetail: AnswerViewProps['evidenceDetail'];
  featured?: boolean;
}) {
  const { t } = useI18n();
  const [expanded, setExpanded] = useState(featured ?? false);

  const locator = formatLocator(citation);

  return (
    <div
      className={cn(
        'rounded-[var(--uxe-radius-card)] border p-3',
        // A verified quotation gets the highlighter treatment. One that could not be
        // re-located gets the failure treatment: it must never be the quieter of the two.
        citation.verified
          ? 'border-[var(--uxe-warning-border)] bg-[var(--uxe-warning-bg)]/40'
          : 'border-[var(--uxe-danger-border)] bg-[var(--uxe-danger-bg)]/40',
      )}
    >
      <div className="flex items-start gap-3">
        <Quote
          className={cn(
            'mt-0.5 h-4 w-4 shrink-0',
            citation.verified ? 'text-[var(--uxe-warning)]' : 'text-[var(--uxe-danger)]',
          )}
          aria-hidden
        />

        <div className="min-w-0 flex-1">
          {evidenceDetail.supportingExcerpt && (
            <button
              type="button"
              onClick={() => setExpanded((v) => !v)}
              aria-expanded={expanded}
              className="block w-full text-start"
            >
              <span
                className={cn(
                  'text-[14px] leading-relaxed text-[var(--uxe-text)] italic',
                  !expanded && 'line-clamp-2',
                )}
              >
                &ldquo;{citation.supportingExcerpt}&rdquo;
              </span>
            </button>
          )}

          <div className="mt-1.5 flex flex-wrap items-center gap-x-2 gap-y-1 text-[12px] text-[var(--uxe-text-secondary)]">
            {evidenceDetail.documentAndPage && (
              <span className="font-medium text-[var(--uxe-text)]">{citation.documentTitle}</span>
            )}
            {evidenceDetail.clauseAndLocation && locator && <span>· {locator}</span>}
            {!citation.verified && (
              <Tooltip content={t('evidence.unverifiedHint')}>
                <button type="button" className="cursor-help">
                  <Badge
                    tone="warning"
                    size="sm"
                    icon={<AlertTriangle className="h-3 w-3" aria-hidden />}
                  >
                    {t('evidence.unverified')}
                  </Badge>
                </button>
              </Tooltip>
            )}
            {citation.entailment === 'contradicts' && (
              <Badge tone="danger" size="sm" icon={<XCircle className="h-3 w-3" aria-hidden />}>
                {t('answer.contradicts')}
              </Badge>
            )}
          </div>
        </div>

        <div className="flex shrink-0 flex-col gap-1.5">
          <Button variant="secondary" size="xs" onClick={() => onOpen(citation.citationId)}>
            {t('consult.openExactPage')}
            <ExternalLink className="h-3 w-3" aria-hidden />
          </Button>
        </div>
      </div>
    </div>
  );
}

function InjectionWarning({ warnings }: { warnings: StructuredAnswer['injectionWarnings'] }) {
  const { t } = useI18n();
  return (
    <div
      role="alert"
      className="flex items-start gap-3 rounded-[var(--uxe-radius-card)] border border-[var(--uxe-danger-border)] bg-[var(--uxe-danger-bg)] p-3.5"
    >
      <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-[var(--uxe-danger)]" aria-hidden />
      <div className="min-w-0">
        <p className="text-[13px] font-semibold text-[var(--uxe-danger)]">
          {t('answer.injectionWarning')}
        </p>
        <ul className="mt-1 space-y-1">
          {warnings.map((warning, index) => (
            <li key={index} className="text-[13px] text-[var(--uxe-text)]">
              <span className="font-medium">{warning.sourceTitle}</span> attempted to influence this
              answer ({warning.pattern}). It has been quarantined and excluded.
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

function pickDecisive(answer: StructuredAnswer, limit: number): Citation[] {
  const decisiveIds = new Set<string>();
  for (const finding of answer.findings) {
    if (finding.result === 'non_compliant' || finding.result === 'needs_evidence') {
      for (const id of finding.governingCitationIds) decisiveIds.add(id);
      for (const id of finding.projectEvidenceCitationIds) decisiveIds.add(id);
    }
  }

  return [...answer.citations]
    .sort((a, b) => {
      if (a.verified !== b.verified) return a.verified ? -1 : 1;
      const aDecisive = decisiveIds.has(a.citationId) ? 1 : 0;
      const bDecisive = decisiveIds.has(b.citationId) ? 1 : 0;
      if (aDecisive !== bDecisive) return bDecisive - aDecisive;
      return b.rerankScore - a.rerankScore;
    })
    .slice(0, limit);
}

export { ChevronDown };

/** "1-3, 7, 9-12" — the sheets a reader can go and check for themselves. */
function formatSheetRanges(sheets: number[]): string {
  const sorted = [...sheets].sort((a, b) => a - b);
  const out: string[] = [];
  let start = sorted[0];
  let previous = sorted[0];
  if (start === undefined || previous === undefined) return '';

  for (const sheet of sorted.slice(1)) {
    if (sheet === previous + 1) {
      previous = sheet;
      continue;
    }
    out.push(start === previous ? `${start}` : `${start}-${previous}`);
    start = sheet;
    previous = sheet;
  }
  out.push(start === previous ? `${start}` : `${start}-${previous}`);
  return out.join(', ');
}
